name: Trigger auto deployment for my-aiops-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-aiops-app-AutoDeployTrigger-8ad9158c-ecdc-4489-b78e-ed9e50033577.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MYAIOPSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYAIOPSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYAIOPSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: myaiopsegistry.azurecr.io
          registryUsername: ${{ secrets.MYAIOPSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYAIOPSAPP_REGISTRY_PASSWORD }}
          containerAppName: my-aiops-app
          resourceGroup: DefaultResourceGroup-null
          imageToBuild: myaiopsegistry.azurecr.io/my-aiops-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


